services:
  - type: web
    name: boldrine-lanches
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: WHATSAPP_NUMBER
        value: "5521988000094"